# version: '3.4'

# services:
#   myfirstblog:
#     image: ${DOCKER_REGISTRY-}myfirstblog
#     build:
#       context: .
#       dockerfile: MyFirstBlog/Dockerfile
version: '3.8'

services:
  myfirstblog:
    build:
      context: .
      dockerfile: MyFirstBlog/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=my_blog;Username=postgres;Password=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_blog
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: