name: Build and deploy Node.js app to Azure Web App - myblogsfrontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
        working-directory: 'Frontend/blog-frontend'  # Path to your frontend app

      - name: Build the React app
        run: npm run build
        working-directory: 'Frontend/blog-frontend'  # Path to your frontend app

      - name: Zip the build folder for deployment
        run: zip -r release.zip ./Frontend/blog-frontend/build  # Ensure you're zipping the correct build folder (usually 'build' or 'dist')

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myblogsfrontend'  # Your Azure Web App name
          slot-name: 'Production'
          package: './Frontend/blog-frontend/dist'  # Path to the React build folder
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_86556FDE771B42749151369FCE6DD01E }}
